<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();
    $_columnCount = 4; //$this->getColumnCount();
    
    $fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // Grid Mode ?>
<div class="home-container grid">
    <div class="meigee-widget">
        <ul class="products-grid widget-grid">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
			<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <li class="grid_3 item">
                <div class="product-img-box">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(298, null); ?>" <?php echo MAGE::helper('ThemeOptions/Retina')->getRetinaData('widget_grid', $_product); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductLabels($_product); ?><span class="image-box"></span><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 298, 600); ?></div></a>
                    <?php // Fancybox
                    if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
                        <a class="fancybox" rel="category-gallery" title="" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
                    <?php endif; // End Fancybox ?>
					<?php if(Mage::getStoreConfig('ajax/general/enabledpro')): ?>
						<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Quick View') ?></span></span></button>
						<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
					<?php endif; ?>
                </div>
				<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php echo $this->getPriceHtml($_product, true) ?>
				<?php if($_product->isSaleable()): ?>
					<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				<?php else: ?>
					<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
				<?php endif; ?>
            </li>
        <?php if ($i+1 == $_collectionSize ) break; $i++; endforeach ?>
        </ul> 
		<script type="text/javascript">
			jQuery(window).load(function(){
				jQuery('.products-grid.widget-grid li.item').each(function(){
					jQuery(this).css('height', jQuery(this).height());
				});
			});
			
			jQuery(document).ready(function(){
			jQuery('.ajax-fancybox').fancybox(
				{
				   hideOnContentClick : true,
				   width:600,
				   autoDimensions: true,
				   type : 'iframe',
				   showTitle: false,
				   scrolling: 'no',
				   afterLoad: function(){
						setTimeout(function(){
							var frameBodyHeight = jQuery('.fancybox-iframe').contents().find('body').height();
							if(jQuery(window).height() > frameBodyHeight+30){
								jQuery('.fancybox-inner').css('height', frameBodyHeight);
							}
						}, 1000);
					}
				}
			);
			
			/* Quick Shop buttons */
			function quickViewButton(){
				jQuery('button.btn-quick-view').each(function(){
					var buttonWidth = jQuery(this).width();
					var imageWidth = jQuery(this).parent().width();
					jQuery(this).css('left', (imageWidth-buttonWidth)/2);
				});
			}
			quickViewButton();
			jQuery(window).resize(function(){
				quickViewButton();
			});
			
		});
		function showOptions(id){
			jQuery('#fancybox'+id).trigger('click');
		}
		function setAjaxData(data,iframe){
			if(data.status == 'ERROR'){
				alert(data.message);
			}else{
				if(jQuery('.top-cart')){
					jQuery('.top-cart').replaceWith(data.sidebar);
				}
				/* if(jQuery('.header .links')){
					jQuery('.header .links').replaceWith(data.toplink);
				} */
				jQuery.fancybox.close();
			}
		}
		function setLocationAjax(url,id){
			url += 'isAjax/1';
			url = url.replace("checkout/cart","ajax/index");
			jQuery('#ajax_loader'+id).show();
			try {
				jQuery.ajax( {
					url : url,
					dataType : 'json',
					success : function(data) {
						jQuery('#ajax_loader'+id).hide();
						setAjaxData(data,false);
					}
				});
			} catch (e) {
			}
		}
		</script>
    </div>
</div>