<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();
    
    $fancybox = MAGE::helper('ThemeOptions')->getThemeOptions('fancybox' );
?>
<?php // List Mode ?>
<ol class="products-list meigee-widget" id="products-list">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <div class="grid_3 alpha">
                <div class="product-img-box">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><div class="hover-box"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(298, null); ?>" <?php echo MAGE::helper('ThemeOptions/Retina')->getRetinaData('widget_list', $_product); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /><?php /* Label New */ echo MAGE::helper('ThemeOptions')->getProductLabels($_product); ?><span class="image-box"></span><?php /* Hover Image */ echo MAGE::helper('ThemeOptions')->getHoverImage($_product, 298, 600); ?></div></a>
                    <?php // Fancybox
                    if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
                        <a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>">&nbsp;</a>
                    <?php endif; // End Fancybox ?>
					<?php if(Mage::getStoreConfig('ajax/general/enabledpro')): ?>
						<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Quick View') ?></span></span></button>
						<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
					<?php endif; ?>
                </div>
            </div>
            <?php // Product description ?>
            <div class="grid_6 omega">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product) ?>
                <?php endif; ?>
                <div class="desc std">
                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                </div>
				<?php echo $this->getPriceHtml($_product, true) ?>
				<?php if(!$_product->isSaleable()): ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                <?php if($_product->isSaleable()): ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                <?php endif; ?>
				<?php 
					$keywords = array('old-price', 'special-price', 'minimal-price-link');
					$pricestring = $this->getPriceHtml($_product, true);
					$isKeyAvaliable = false;
					foreach($keywords as $word){
						if(strpos($pricestring, $word)){
							$isKeyAvaliable = true;
						}
					}
				?>
				<ul class="add-to-links <?php if($isKeyAvaliable == true){echo 'short';} ?>">
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><span>&nbsp;</span><?php echo $this->__('Add to Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><span>&nbsp;</span><?php echo $this->__('Add to Compare') ?></a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </li>
    <?php if (++$i == $_collectionSize ) break; endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
	<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery('.ajax-fancybox').fancybox(
				{
				   hideOnContentClick : true,
				   width:600,
				   autoDimensions: true,
				   type : 'iframe',
				   showTitle: false,
				   scrolling: 'no',
				   afterLoad: function(){
						setTimeout(function(){
							var frameBodyHeight = jQuery('.fancybox-iframe').contents().find('body').height();
							if(jQuery(window).height() > frameBodyHeight+30){
								jQuery('.fancybox-inner').css('height', frameBodyHeight);
							}
						}, 1000);
					}
				}
			);
			
			/* Quick Shop buttons */
			function quickViewButton(){
				jQuery('button.btn-quick-view').each(function(){
					var buttonWidth = jQuery(this).width();
					var imageWidth = jQuery(this).parent().width();
					jQuery(this).css('left', (imageWidth-buttonWidth)/2);
				});
			}
			quickViewButton();
			jQuery(window).resize(function(){
				quickViewButton();
			});
			
		});
		function showOptions(id){
			jQuery('#fancybox'+id).trigger('click');
		}
		function setAjaxData(data,iframe){
			if(data.status == 'ERROR'){
				alert(data.message);
			}else{
				if(jQuery('.top-cart')){
					jQuery('.top-cart').replaceWith(data.sidebar);
				}
				/* if(jQuery('.header .links')){
					jQuery('.header .links').replaceWith(data.toplink);
				} */
				jQuery.fancybox.close();
			}
		}
		function setLocationAjax(url,id){
			url += 'isAjax/1';
			url = url.replace("checkout/cart","ajax/index");
			jQuery('#ajax_loader'+id).show();
			try {
				jQuery.ajax( {
					url : url,
					dataType : 'json',
					success : function(data) {
						jQuery('#ajax_loader'+id).hide();
						setAjaxData(data,false);
					}
				});
			} catch (e) {
			}
		}
	</script>